export const CONNECTION = 'CONNECTION';
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const CONNECTION_FAIL = 'CONNECTION_FAIL';

export const USER_STATUS = 'USER_STATUS';
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS';
export const USER_STATUS_FAIL = 'USER_STATUS_FAIL';

export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';

export const ROOM_LIST = 'ROOM_LIST';

export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_FAIL = 'JOIN_ROOM_FAIL';

export const LEAVE_ROOM = 'LEAVE_ROOM';
export const LEAVE_ROOM_SUCCESS = 'LEAVE_ROOM_SUCCESS';
export const LEAVE_ROOM_FAIL = 'LEAVE_ROOM_FAIL';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL';
